###
POST http://localhost:3000/addPeer
Content-Type: application/json

{
    "peer": "ws://localhost:4001"
}

###

GET http://localhost:3000/blocks

###

POST http://localhost:3000/mineTransaction
Content-Type: application/json

{
    "address": "04aeeab6dcf3d725db209d58eb7d25f94579dcc55d9773f457cc77517edec0a3ec2fe10ca03e9981c7f628c6118ab2b3c4a69f87038c8ffeb18708169ecaaeec9d",
    "amount": 10
}


###
GET http://localhost:3000/me/balance


###

POST http://localhost:3000/transactions
Content-Type: application/json

{
    "address": "04eeeab6dcf3d725db209d58eb7d25f94579dcc55d9773f457cc77517edec0a3ec2fe10ca03e9981c7f628c6118ab2b3c4a69f87038c8ffeb18708169ecaaeec9d",
    "amount": 500
}


###

POST http://localhost:62416/mine
Content-Type: application/json